.

diff --git a/vars/images b/vars/images
--- a/vars/images
+++ b/vars/images
@@ -1,6 +1,5 @@
 images:
 - name: base
-  tag: "{{ builder.portage }}"
   section: local
   type: gentoo-image-builder
   test: sh -c 'busybox sh --help'
@@ -18,12 +17,21 @@ images:
     user: postgres
     packages: ="{{ software.postgresql.latest.params.repo }}"-"{{ software.postgresql.version }}"
     finish_rootfs_build: |
-      ln -s usr/lib "${ROOT}/lib" && copy_gcc_libs
+      ln -s usr/lib "${ROOT}/lib" # && copy_gcc_libs
       (cd ${ROOT}; for f in usr/lib/postgresql*/bin/*; do ln -s /$f usr/bin/; done)
       mkdir -p -m 3777 ${ROOT}/run/postgresql && chown postgres ${ROOT}/run/postgresql
-    
+
+- name: pg_migrate
+  tag: 17to18
+  section: db
+  type: gentoo-image-builder
+  requires: 
+  - base
+  build:
+    user: postgres
+    packages: "={{ software.postgresql.latest.params.repo }}-17.6-r1 ={{ software.postgresql.latest.params.repo }}-18.0"
+
 - name: go
-  tag: 2025.05-1
   section: local
   type: gentoo-image-builder
   requires:
@@ -122,11 +130,8 @@ images:
       rm -rf distribution /root/.??* /root/*
 
 - name: nodejs
-  tag: "{{ builder.portage }}"
   section: local
   type: gentoo-image-builder
-  env:
-     XXXLDFLAGS: "-static-libgcc -static-libstdc++"
   requires:
   - base
   build:
@@ -134,15 +139,13 @@ images:
     configure_builder: |
       echo "net-libs/nodejs npm" >> /etc/portage/package.use/97nodejs.conf
       echo "dev-lang/typescript ~arm64" > /etc/portage/package.accept_keywords/ts.conf && cat /etc/portage/package.accept_keywords/ts.conf
-      emerge net-libs/nodejs dev-lang/typescript
+      MAKEOPTS="-j1" emerge --tree --verbose net-libs/nodejs dev-lang/typescript
     configure_rootfs_build: |
-      #provide_package sys-devel/gcc
       ln -s usr/lib "${ROOT}/lib"
     finish_rootfs_build: |
       ln -s ../../bin/env "${ROOT}/usr/bin/env"
 
 - name: idp
-  tag: 2025.3
   section: auth
   type: gentoo-image-builder
   requires:
@@ -151,11 +154,11 @@ images:
   build:
     entrypoint: ["/bin/sh", "-c", "npm run serve"]
     configure_rootfs_build: |
+      git_url="https://github.com/cainam/sufficient_idp.git"
       git=$(basename "{{ own_git_url }}" | sed -e 's/\.git$//g')
-      git clone --branch master --depth 1 --filter=blob:none --sparse "{{ own_git_url }}"
-      ( cd "${git}" && git sparse-checkout set hydra-login-consent-node
-        mkdir "${ROOT}/app" && mv  hydra-login-consent-node/* "${ROOT}/app/"
-      ) && rm -rf "${git}"
+      git clone --single-branch --branch main --depth 1 --filter=blob:none "${git_url}"
+      mkdir -p "${ROOT}/app" && mv sufficient_idp/idp/* "${ROOT}/app/"
+      rm -rf "${git}"
     finish_rootfs_build: |
       cd "${ROOT}/app/"
       npm ci && npm run build
@@ -197,7 +200,6 @@ images:
     finish_rootfs_build: strip "${ROOT}/usr/bin/helm"
   
 - name: python3
-  tag: 2025.09-2
   section: local
   requires:
   - base
@@ -218,7 +220,6 @@ images:
     finish_rootfs_build: mkdir -p "${ROOT}/usr/local/lib"; for lib in $(find /usr/lib/ -name libgomp.so.1); do cp "${lib}" "${ROOT}/usr/local/lib"; done
 
 - name: ha-base
-  tag: 2025.10
   section: home
   requires:
   - python3
@@ -293,18 +294,107 @@ images:
       echo "mosquitto:x:1883:1883:mosquitto:/var/empty:/sbin/nologin" >> ${ROOT}/etc/passwd
       strip ${ROOT}/usr/lib/* ${ROOT}/usr/bin/* ${ROOT}/usr/sbin/* || true
 
+- name: bazel2
+  tag: 2025.09-1
+  section: local
+  requires:
+  - bazel
+  type: gentoo-image-builder
+  env:
+    JAVA_HOME: /opt/zulu
+    USER: root
+  build:
+    finish_rootfs_build: |
+      mkdir $ROOT/usr/local/bin $ROOT/opt/
+      cp -rdp /opt/zulu $ROOT/opt/zulu
+      cp -dp /usr/lib/gcc/aarch64-unknown-linux-musl/14/libstdc++.so.6* /usr/lib/gcc/aarch64-unknown-linux-musl/14/libgcc_s.so.1* $ROOT/usr/lib
+      cp -dp /usr/local/bin/bazel $ROOT/usr/local/bin/
+
 - name: bazel
-  tag: 2025.02-1
+  tag: 2025.09-1
   section: local
   requires:
   - python3
   type: gentoo-image-builder
+  env:
+    JAVA_HOME: /opt/zulu
+    USER: root
   build:
-    packages: app-arch/zip virtual/jdk
-    configure_rootfs_build: |
-      git clone --depth=1 -b "8.1.1" https://github.com/bazelbuild/bazel.git
+    packages: app-arch/zip
+    configure_builder: emerge app-arch/zip
+    finish_rootfs_build: |
+      zulu=zulu21.46.19-ca-jdk21.0.9-linux_musl_aarch64.tar.gz
+      ZULU_DIR=/opt/zulu
+      curl -O https://cdn.azul.com/zulu/bin/$zulu
+      mkdir -p "${ZULU_DIR}" && tar --directory "${ZULU_DIR}" --extract --strip-components=1 --file  $zulu
+      export  JAVA_HOME=$ZULU_DIR
+      export PATH=$JAVA_HOME/bin:$PATH
+
+      bazel_version=8.4.2
+      bazel_dist=bazel-$bazel_version-dist.zip
+      mkdir /bazel
       cd bazel
-      env EXTRA_BAZEL_ARGS="--tool_java_runtime_version=local_jdk" bash ./compile.sh.
+      curl -L -O https://github.com/bazelbuild/bazel/releases/download/$bazel_version/$bazel_dist
+      unzip -q $bazel_dist
+      curl "https://gitlab.alpinelinux.org/alpine/aports/-/raw/e49daeab5c9554e8cb7ca23547037d6659d7be43/testing/bazel8/0001-off64t-fix.patch?inline=false" -O
+
+      # 8.4 bazel zip, patch applied, but script/BUILD failed, ignored
+      patch -p1 < 0001-off64t-fix.patch || true
+      EXTRA_BAZEL_ARGS="--tool_java_runtime_version=local_jdk" bash ./compile.sh
+      mkdir $ROOT/usr/local/bin $ROOT/opt/
+      cp -rdp /opt/zulu $ROOT/opt/zulu
+      cp -dp /usr/lib/gcc/aarch64-unknown-linux-musl/14/libstdc++.so.6* /usr/lib/gcc/aarch64-unknown-linux-musl/14/libgcc_s.so.1* $ROOT/usr/lib
+      cp -dp output/bazel $ROOT/usr/local/bin /usr/local/bin/
+ 
+- name: bazel7-llvm
+  tag: 2025.09-1
+  section: local
+  requires:
+  - bazel7
+  type: gentoo-image-builder
+  build:
+    configure_builder: emerge llvm-core/clang llvm-runtimes/libcxx
+    finish_rootfs_build: |
+      cp -dp /bazel/output/bazel /usr/local/bin/
+
+- name: bazel7
+  tag: 2025.09-1
+  section: local
+  requires:
+  - python3
+  type: gentoo-image-builder
+  env:
+    JAVA_HOME: /opt/zulu
+    USER: root
+  build:
+    packages: app-arch/zip
+    configure_builder: emerge app-arch/zip
+    finish_rootfs_build: |
+      zulu=zulu21.46.19-ca-jdk21.0.9-linux_musl_aarch64.tar.gz
+      ZULU_DIR=/opt/zulu
+      curl -O https://cdn.azul.com/zulu/bin/$zulu
+      mkdir -p "${ZULU_DIR}" && tar --directory "${ZULU_DIR}" --extract --strip-components=1 --file  $zulu
+      export  JAVA_HOME=$ZULU_DIR
+      export PATH=$JAVA_HOME/bin:$PATH
+
+      bazel_version=7.6.1
+      bazel_dist=bazel-$bazel_version-dist.zip
+      mkdir /bazel
+      cd bazel
+      curl -L -O https://github.com/bazelbuild/bazel/releases/download/$bazel_version/$bazel_dist
+      unzip -q $bazel_dist
+      #curl "https://gitlab.alpinelinux.org/alpine/aports/-/raw/e49daeab5c9554e8cb7ca23547037d6659d7be43/testing/bazel8/0001-off64t-fix.patch?inline=false" -O
+      curl "https://gitlab.alpinelinux.org/alpine/aports/-/raw/e49daeab5c9554e8cb7ca23547037d6659d7be43/testing/bazel7/0001-off64t-fix.patch?inline=false" -O 
+
+      # 8.4 bazel zip, patch applied, but script/BUILD failed, ignored
+      patch -p1 < 0001-off64t-fix.patch || true
+      sed -i -e 's/"abseil-cpp", version = "20230125.1"/"abseil-cpp", version = "20230802.0"/' MODULE.bazel
+
+      EXTRA_BAZEL_ARGS="--tool_java_runtime_version=local_jdk" bash ./compile.sh
+      mkdir $ROOT/usr/local/bin $ROOT/opt/
+      cp -rdp /opt/zulu $ROOT/opt/zulu
+      cp -dp /usr/lib/gcc/aarch64-unknown-linux-musl/14/libstdc++.so.6* /usr/lib/gcc/aarch64-unknown-linux-musl/14/libgcc_s.so.1* $ROOT/usr/lib
+      cp -dp output/bazel $ROOT/usr/local/bin
  
 - name: auth-operator
   tag: 2025.04
@@ -320,7 +410,6 @@ images:
       mv "$VIRTUAL_ENV" ${ROOT}/"$VIRTUAL_ENV"
       
 - name: fastapi
-  tag: 2025.06-1
   section: local
   requires:
   - python3
